/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.4, Verify behaviour of port.check(catch) with assignment in case of successful match in standalone statement
 ** @verdict  pass accept, ttcn3verdict:pass
 *****************************************************************/
module Sem_2204_the_check_operation_092 {

	signature S() exception(integer);
	type port P procedure {
		inout S;
	}

    type component GeneralComp {
		port P p;
	}

	function f() runs on GeneralComp {
		p.getcall;
		setverdict(pass, "Call received");
		p.raise(S, integer:1);
	}

	testcase TC_Sem_2204_the_check_operation_092() runs on GeneralComp system GeneralComp{
		var GeneralComp v_ptc := GeneralComp.create, v_src;
		var integer v_val;
		connect(self:p, v_ptc:p);
		p.call(S:{}, nowait);
		v_ptc.start(f());
        alt
		{
        	[] p.check(catch(S, integer: complement(4, 5, 6)) -> value v_val sender v_src) {
				if (match(v_val, 1) and match(v_src, v_ptc)) { setverdict(pass, "Check operation successful"); }
				else { setverdict(fail, "Incorrect exception value or sender"); }
			}
		}
		p.catch;
		setverdict(pass, "Exception still on the top of the queue");
    }

    control {
        execute(TC_Sem_2204_the_check_operation_092(), 5.0);
    }
}