/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.4, Verify behaviour of port.check(catch) in case of unsuccessful match in standalone statement
 ** @verdict  pass accept, ttcn3verdict:pass
 *****************************************************************/
module Sem_2204_the_check_operation_083 {

	signature S() exception(integer);
	type port P procedure {
		inout S;
	}

    type component GeneralComp {
		port P p;
	}

	function f() runs on GeneralComp {
		p.getcall;
		setverdict(pass, "Call received");
		p.raise(S, integer:1);
	}

	altstep a() runs on GeneralComp {
		[] p.catch {
			setverdict(pass, "As expected, the check operation didn't match");
			stop;
		}
	}

	testcase TC_Sem_2204_the_check_operation_083() runs on GeneralComp system GeneralComp{
		var GeneralComp v_ptc := GeneralComp.create;
		activate(a());
		connect(self:p, v_ptc:p);
		p.call(S:{}, nowait);
		v_ptc.start(f());
        p.check(catch(S, integer:?) from self);
		setverdict(fail, "Incorrect match");
    }

    control {
        execute(TC_Sem_2204_the_check_operation_083(), 5.0);
    }
}