/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.4, Verify that port.check(catch) works correctly as standalone statement
 ** @verdict  pass accept, ttcn3verdict:pass
 *****************************************************************/
module Sem_2204_the_check_operation_075 {

	signature S() exception(integer);
	type port P procedure {
		inout S;
	}

    type component GeneralComp {
		port P p;
	}

	function f() runs on GeneralComp {
		p.getcall;
		setverdict(pass, "Call received");
		p.raise(S, integer:1);
	}

	testcase TC_Sem_2204_the_check_operation_075() runs on GeneralComp system GeneralComp{
		var GeneralComp v_ptc := GeneralComp.create;
		connect(self:p, v_ptc:p);
		p.call(S:{}, nowait);
		v_ptc.start(f());
        p.check(catch);
		setverdict(pass, "Check operation successful");
		p.catch;
		setverdict(pass, "Exception still on the top of the queue");
    }

    control {
        execute(TC_Sem_2204_the_check_operation_075(), 5.0);
    }
}