/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.3.6, Verify that error occurs when any from catch is applied to 1D array and index target has wrong type
 ** @verdict  pass reject
 *****************************************************************/
// The following requirements are tested:
// The catch on any port from a port array operation can not be used to catch a call timeout.
module NegSyn_220306_catch_operation_003 {

	signature S() exception(integer);

	type port P procedure {
		inout S;
	}

	const integer c_portCount := 4;
    type component GeneralComp
	{
		port P p[c_portCount];
	}

	function f() runs on GeneralComp
	{
		for(var integer i := 0; i < c_portCount; i := i + 1) {
			p[i].getcall;
			if (i mod 2 == 1) { p[i].raise(S, 10) };
		}
	}

    testcase TC_NegSyn_220306_catch_operation_003() runs on GeneralComp system GeneralComp {
		var GeneralComp v_ptc := GeneralComp.create;
		var float v_index;
		for(var integer i := 0; i < c_portCount; i := i + 1) {
			connect(self:p[i], v_ptc:p[i]);
			p[i].call(S:{}, 1.0) {
				[]any from p.catch(timeout) { setverdict(pass); }
			}
		}

	}

    control {
        execute(TC_NegSyn_220306_catch_operation_003(), 5.0);
    }
}